// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdalawzjpqkfemiwhlpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkYWxhd3pqcHFrZmVtaXdobHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODc0NzQsImV4cCI6MjA2OTM2MzQ3NH0.voRlMliRPUC-U4bGs-2JaJZVkRjaYCPA-Dz6fVXCcMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});